### ISSUE TITLE
pod cannot start on EKS 

### ISSUE THREAD

**Issue by angelwcrypto** [kubecost/cluster-turndown#51]
Hello, 

I have the similar issue with previous users with EKS, followed completely with IAM policies with autoscaling full control, eks privileges and same secret in the document. However the pod cannot even start and seems like the client cannot recognise the provider. 

Thank you .

I0616 08:12:54.345492       1 main.go:118] Running Kubecost Turndown on: ip-xxxxxxxxxx.xxxxxxx.compute.internal
I0616 08:12:54.363880       1 clusterprovider.go:92] Found ProviderID starting with "aws" and eks nodegroup, using EKS Provider
I0616 08:12:54.399739       1 main.go:133] [Error]: Failed to create ClusterProvider: UnrecognizedClientException: 
	status code: 403, request id: 4ba56060-d2aa-4368-9e13-fd9d9cb24c81
I0616 08:13:08.966637       1 main.go:118] Running Kubecost Turndown on: ip-xxxxxxxxxx.xxxxxxx.compute.internal
I0616 08:13:08.984976       1 clusterprovider.go:92] Found ProviderID starting with "aws" and eks nodegroup, using EKS Provider
I0616 08:13:09.029962       1 main.go:133] [Error]: Failed to create ClusterProvider: UnrecognizedClientException: 
	status code: 403, request id: 788fd61f-597c-4bd5-9686-69c3565ed8d5

**Comment by michaelmdresser** [comment]
Hi @angelwcrypto did you manage to get cluster-turndown working, or are you still encountering problems?
